import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import type { BasicProfile } from "@datamodels/identity-profile-basic";

import ceramicLogo from '../public/ceramic.png'
import { useCeramicContext } from '../context'
import { authenticateCeramic } from '../utils'
import Hero from '../components/hero';
import NavBar from '../components/navbar';
import Footer from '../components/footer';

const Home: NextPage = () => {
  const clients = useCeramicContext()
  const { ceramic, composeClient } = clients
  const [profile, setProfile] = useState<BasicProfile | undefined>()
  const [loading, setLoading] = useState<boolean>(false)

  const handleLogin = async () => {
    await authenticateCeramic(ceramic, composeClient)
    await getProfile()
  }

  const getProfile = async () => {
    setLoading(true)
    if(ceramic.did !== undefined) {
      const profile = await composeClient.executeQuery(`
        query {
          viewer {
            basicProfile {
              id
              name
              description
              gender
              emoji
            }
          }
        }
      `);
      
      setProfile(profile?.data?.viewer?.basicProfile)
      setLoading(false);
    }
  }
  
  const updateProfile = async () => {
    setLoading(true);
    if (ceramic.did !== undefined) {
      const update = await composeClient.executeQuery(`
        mutation {
          createBasicProfile(input: {
            content: {
              name: "${profile?.name}"
              description: "${profile?.description}"
              gender: "${profile?.gender}"
              emoji: "${profile?.emoji}"
            }
          }) 
          {
            document {
              name
              description
              gender
              emoji
            }
          }
        }
      `);
      await getProfile();
      setLoading(false);
    }
  }
  
  /**
   * On load check if there is a DID-Session in local storage.
   * If there is a DID-Session we can immediately authenticate the user.
   * For more details on how we do this check the 'authenticateCeramic function in`../utils`.
   */
  useEffect(() => {
    if(localStorage.getItem('did')) {
      handleLogin()
    }
  }, [ ])

  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create ceramic app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Hero />

      {/* <main className="">
        <h1 className="">Your Decentralized Profile</h1>
        <Image
          src={ceramicLogo}
          width="100"
          height="100"
          className=""
          alt=""
        />
        {profile === undefined && ceramic.did === undefined ? (
          <button
            onClick={() => {
              handleLogin();
            }}
          >
            Login
          </button>
        ) : (
          <div className="">
            <div className="">
              <label>Name</label>
              <input
                type="text"
                className="input input-bordered input-primary w-full max-w-xs"
                defaultValue={profile?.name || ''}
                onChange={(e) => {
                  setProfile({ ...profile, name: e.target.value });
                }}
              />
            </div>
            <div className="">
              <label>Description</label>
              <input
                type="text"
                className="input input-bordered input-primary w-full max-w-xs"
                defaultValue={profile?.description || ''}
                onChange={(e) => {
                  setProfile({ ...profile, description: e.target.value });
                }}
              />
            </div>
            <div className="">
              <label>Gender</label>
              <input
                type="text"
                className="input input-bordered input-primary w-full max-w-xs"
                defaultValue={profile?.gender || ''}
                onChange={(e) => {
                  setProfile({ ...profile, gender: e.target.value });
                }}
              />
            </div>
            <div className="">
              <label>Emoji</label>
              <input
                type="text"
                className="input input-bordered input-primary w-full max-w-xs"
                defaultValue={profile?.emoji || ''}
                onChange={(e) => {
                  setProfile({ ...profile, emoji: e.target.value });
                }}
                maxLength={2}
              />
            </div>
            <div className="">
              <button
              onClick={() => {
                updateProfile();
              }}>
                {loading ? 'Loading...' : 'Update Profile'}
              </button>
            </div>
          </div>
        )}
      </main> */}
      <Footer />
    </div>
  );
}

export default Home
