import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/hero';
import NavBar from '../components/navbar';
import Footer from '../components/footer';

const Home: NextPage = () => {
  
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create ceramic app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Hero />
      <Footer />
    </div>
  );
}

export default Home
